# Ce fichier a été auto-généré par Firebase CLI
# https://github.com/firebase/firebase-tools

name: Deploy Flutter App to Firebase Hosting on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Récupération du code source
      - uses: actions/checkout@v4

      # Étape 2 : Installer Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # Utilisez la version stable de Flutter

      # Étape 3 : Installer les dépendances Flutter
      - name: Install Flutter dependencies
        run: flutter pub get

      # Étape 4 : Construire l'application Flutter pour le web
      - name: Build Flutter for web
        run: flutter build web  # Utilisez 'flutter build apk' pour Android, ou 'flutter build ios' pour iOS

      # Étape 5 : Déployer sur Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DIGTOR253 }}
          projectId: digtor253
